Update Github Issue Template Workflow
nimblehq/git-template pull request #9
Opened 2020-09-10 06:17 UTC by rafayet-monon

https://github.com/nimblehq/git-template/issues/8

## What happened

Update the Github issue template workflow to a newer version.

## Insight

Currently, this repo has the older version of the issue template workflow. As Github introduced the new issue template workflow we can update to a newer version.
 
## Proof Of Work

A [test Github repository](https://github.com/rafayet-monon/git-template-issue-test) created from the [forked repository](https://github.com/rafayet-monon/git-template) and this PR branch was used as default.

[Issue templates ](https://github.com/rafayet-monon/git-template-issue-test/issues/new/choose) to choose from -

![image](https://user-images.githubusercontent.com/14927672/92688565-5dd67580-f35f-11ea-8fa3-ad123053bf54.png)

2020-09-10 15:49 UTC, hoangmirs approved these changes
LGTM

2020-09-11 04:28 UTC, olivierobert requested changes
I think we should keep just the bug and feature templates

2020-09-11 04:28 UTC, olivierobert commented on .github/ISSUE_TEMPLATE/rfc_template.md
> +name: "Request For Comments (RFC)"
This template is not needed here. It was made solely to discuss process changes on Compass.

2020-09-11 04:28 UTC, olivierobert commented on .github/ISSUE_TEMPLATE/content_template.md
> +name: "Content"
This template is not needed here. It was made solely to propose new content pages on Compass.

2020-09-11 05:50 UTC, rafayet-monon commented on .github/ISSUE_TEMPLATE/rfc_template.md
> +name: "Request For Comments (RFC)"
deleted in [ce1d276](https://github.com/nimblehq/git-template/pull/9/commits/ce1d2767b8b1ec393a35c50a0b17c09c8cb7eb37)

2020-09-11 05:50 UTC, rafayet-monon commented on .github/ISSUE_TEMPLATE/content_template.md
> +name: "Content"
deleted in [ce1d276](https://github.com/nimblehq/git-template/pull/9/commits/ce1d2767b8b1ec393a35c50a0b17c09c8cb7eb37)

2020-10-05 10:24 UTC, olivierobert approved these changes

2020-10-05 10:24 UTC, merged